export const DEFAULT_PRODUCT_LIST = [
  // 🥚 유제품/계란 (통합)
  { name: '계란', category: '유제품/계란' },
  { name: '메추리알', category: '유제품/계란' },
  { name: '흰자', category: '유제품/계란' },
  { name: '노른자', category: '유제품/계란' },
  { name: '우유', category: '유제품/계란' },
  { name: '저지방 우유', category: '유제품/계란' },
  { name: '무지방 우유', category: '유제품/계란' },
  { name: '두유', category: '유제품/계란' },
  { name: '아몬드밀크', category: '유제품/계란' },
  { name: '오트밀크', category: '유제품/계란' },
  { name: '버터', category: '유제품/계란' },
  { name: '무염버터', category: '유제품/계란' },
  { name: '가염버터', category: '유제품/계란' },
  { name: '마가린', category: '유제품/계란' },
  { name: '생크림', category: '유제품/계란' },
  { name: '휘핑크림', category: '유제품/계란' },
  { name: '요거트', category: '유제품/계란' },
  { name: '플레인 요거트', category: '유제품/계란' },
  { name: '그릭 요거트', category: '유제품/계란' },
  { name: '요구르트', category: '유제품/계란' },
  { name: '슬라이스 치즈', category: '유제품/계란' },
  { name: '모짜렐라 치즈', category: '유제품/계란' },
  { name: '체다 치즈', category: '유제품/계란' },
  { name: '고다 치즈', category: '유제품/계란' },
  { name: '파마산 치즈', category: '유제품/계란' },
  { name: '크림치즈', category: '유제품/계란' },
  { name: '리코타 치즈', category: '유제품/계란' },

  // 🥩 육류
  { name: '돼지고기', category: '육류' },
  { name: '삼겹살', category: '육류' },
  { name: '목살', category: '육류' },
  { name: '앞다리살', category: '육류' },
  { name: '뒷다리살', category: '육류' },
  { name: '돼지갈비', category: '육류' },
  { name: '항정살', category: '육류' },
  { name: '가브리살', category: '육류' },
  { name: '소고기', category: '육류' },
  { name: '소고기 등심', category: '육류' },
  { name: '소고기 안심', category: '육류' },
  { name: '소고기 채끝', category: '육류' },
  { name: '소고기 갈비', category: '육류' },
  { name: '양지', category: '육류' },
  { name: '사태', category: '육류' },
  { name: '차돌박이', category: '육류' },
  { name: '우둔살', category: '육류' },
  { name: '닭고기', category: '육류' },
  { name: '닭가슴살', category: '육류' },
  { name: '닭다리', category: '육류' },
  { name: '닭봉', category: '육류' },
  { name: '닭날개', category: '육류' },
  { name: '오리고기', category: '육류' },
  { name: '오리훈제', category: '육류' },
  { name: '양고기', category: '육류' },
  { name: '베이컨', category: '육류' },
  { name: '햄', category: '육류' },
  { name: '소시지', category: '육류' },
  { name: '비엔나 소시지', category: '육류' },
  { name: '초리조', category: '육류' },

  // 🐟 수산물
  { name: '고등어', category: '수산물' },
  { name: '삼치', category: '수산물' },
  { name: '갈치', category: '수산물' },
  { name: '꽁치', category: '수산물' },
  { name: '연어', category: '수산물' },
  { name: '참치', category: '수산물' },
  { name: '대구', category: '수산물' },
  { name: '명태', category: '수산물' },
  { name: '동태', category: '수산물' },
  { name: '황태', category: '수산물' },
  { name: '아귀', category: '수산물' },
  { name: '장어', category: '수산물' },
  { name: '오징어', category: '수산물' },
  { name: '문어', category: '수산물' },
  { name: '낙지', category: '수산물' },
  { name: '쭈꾸미', category: '수산물' },
  { name: '새우', category: '수산물' },
  { name: '대하', category: '수산물' },
  { name: '꽃게', category: '수산물' },
  { name: '대게', category: '수산물' },
  { name: '홍합', category: '수산물' },
  { name: '바지락', category: '수산물' },
  { name: '모시조개', category: '수산물' },
  { name: '가리비', category: '수산물' },
  { name: '전복', category: '수산물' },
  { name: '소라', category: '수산물' },
  { name: '해물믹스', category: '수산물' },
  { name: '멸치', category: '수산물' },
  { name: '다시마', category: '수산물' },
  { name: '미역', category: '수산물' },
  { name: '김', category: '수산물' },
  { name: '북어채', category: '수산물' },
  { name: '오징어채', category: '수산물' },

  // 🥦 채소
  { name: '양파', category: '채소' },
  { name: '마늘', category: '채소' },
  { name: '대파', category: '채소' },
  { name: '쪽파', category: '채소' },
  { name: '부추', category: '채소' },
  { name: '감자', category: '채소' },
  { name: '고구마', category: '채소' },
  { name: '당근', category: '채소' },
  { name: '무', category: '채소' },
  { name: '배추', category: '채소' },
  { name: '양배추', category: '채소' },
  { name: '상추', category: '채소' },
  { name: '깻잎', category: '채소' },
  { name: '시금치', category: '채소' },
  { name: '청경채', category: '채소' },
  { name: '로메인', category: '채소' },
  { name: '케일', category: '채소' },
  { name: '치커리', category: '채소' },
  { name: '오이', category: '채소' },
  { name: '애호박', category: '채소' },
  { name: '주키니', category: '채소' },
  { name: '단호박', category: '채소' },
  { name: '토마토', category: '채소' },
  { name: '방울토마토', category: '채소' },
  { name: '파프리카', category: '채소' },
  { name: '피망', category: '채소' },
  { name: '가지', category: '채소' },
  { name: '옥수수', category: '채소' },
  { name: '버섯', category: '채소' },
  { name: '표고버섯', category: '채소' },
  { name: '느타리버섯', category: '채소' },
  { name: '새송이버섯', category: '채소' },
  { name: '팽이버섯', category: '채소' },
  { name: '양송이버섯', category: '채소' },

  // 🍎 과일
  { name: '사과', category: '과일' },
  { name: '배', category: '과일' },
  { name: '바나나', category: '과일' },
  { name: '귤', category: '과일' },
  { name: '오렌지', category: '과일' },
  { name: '레몬', category: '과일' },
  { name: '라임', category: '과일' },
  { name: '자몽', category: '과일' },
  { name: '포도', category: '과일' },
  { name: '청포도', category: '과일' },
  { name: '딸기', category: '과일' },
  { name: '블루베리', category: '과일' },
  { name: '라즈베리', category: '과일' },
  { name: '키위', category: '과일' },
  { name: '파인애플', category: '과일' },
  { name: '망고', category: '과일' },
  { name: '수박', category: '과일' },
  { name: '멜론', category: '과일' },
  { name: '체리', category: '과일' },
  { name: '복숭아', category: '과일' },
  { name: '자두', category: '과일' },

  // 🌾 곡류/면류
  { name: '쌀', category: '곡류/면류' },
  { name: '현미', category: '곡류/면류' },
  { name: '찹쌀', category: '곡류/면류' },
  { name: '잡곡', category: '곡류/면류' },
  { name: '귀리', category: '곡류/면류' },
  { name: '보리', category: '곡류/면류' },
  { name: '밀가루', category: '곡류/면류' },
  { name: '중력분', category: '곡류/면류' },
  { name: '강력분', category: '곡류/면류' },
  { name: '박력분', category: '곡류/면류' },
  { name: '부침가루', category: '곡류/면류' },
  { name: '튀김가루', category: '곡류/면류' },
  { name: '빵가루', category: '곡류/면류' },
  { name: '식빵', category: '곡류/면류' },
  { name: '바게트', category: '곡류/면류' },
  { name: '또띠아', category: '곡류/면류' },
  { name: '파스타면', category: '곡류/면류' },
  { name: '스파게티', category: '곡류/면류' },
  { name: '펜네', category: '곡류/면류' },
  { name: '라자냐면', category: '곡류/면류' },
  { name: '국수', category: '곡류/면류' },
  { name: '소면', category: '곡류/면류' },
  { name: '중면', category: '곡류/면류' },
  { name: '칼국수면', category: '곡류/면류' },
  { name: '우동면', category: '곡류/면류' },
  { name: '라면', category: '곡류/면류' },

  // 🧂 양념/소스
  { name: '소금', category: '양념/소스' },
  { name: '설탕', category: '양념/소스' },
  { name: '흑설탕', category: '양념/소스' },
  { name: '꿀', category: '양념/소스' },
  { name: '올리고당', category: '양념/소스' },
  { name: '후추', category: '양념/소스' },
  { name: '간장', category: '양념/소스' },
  { name: '진간장', category: '양념/소스' },
  { name: '국간장', category: '양념/소스' },
  { name: '양조간장', category: '양념/소스' },
  { name: '고추장', category: '양념/소스' },
  { name: '된장', category: '양념/소스' },
  { name: '쌈장', category: '양념/소스' },
  { name: '식용유', category: '양념/소스' },
  { name: '올리브오일', category: '양념/소스' },
  { name: '카놀라유', category: '양념/소스' },
  { name: '참기름', category: '양념/소스' },
  { name: '들기름', category: '양념/소스' },
  { name: '식초', category: '양념/소스' },
  { name: '발사믹식초', category: '양념/소스' },
  { name: '고춧가루', category: '양념/소스' },
  { name: '다진마늘', category: '양념/소스' },
  { name: '다진생강', category: '양념/소스' },
  { name: '마요네즈', category: '양념/소스' },
  { name: '케첩', category: '양념/소스' },
  { name: '머스터드', category: '양념/소스' },
  { name: '굴소스', category: '양념/소스' },
  { name: '데리야끼소스', category: '양념/소스' },
  { name: '스리라차', category: '양념/소스' },
  { name: '칠리소스', category: '양념/소스' },
  { name: '토마토소스', category: '양념/소스' },
  { name: '간장소스', category: '양념/소스' },
  { name: '치킨스톡', category: '양념/소스' },
  { name: '다시다', category: '양념/소스' },
  { name: '미원', category: '양념/소스' },
  { name: '연두', category: '양념/소스' },
  { name: '혼다시', category: '양념/소스' },

  // 🧊 가공/냉동
  { name: '두부', category: '가공/냉동' },
  { name: '순두부', category: '가공/냉동' },
  { name: '유부', category: '가공/냉동' },
  { name: '어묵', category: '가공/냉동' },
  { name: '맛살', category: '가공/냉동' },
  { name: '햄버거패티', category: '가공/냉동' },
  { name: '냉동만두', category: '가공/냉동' },
  { name: '냉동피자', category: '가공/냉동' },
  { name: '냉동치킨', category: '가공/냉동' },
  { name: '냉동감자', category: '가공/냉동' },
  { name: '냉동야채', category: '가공/냉동' },
  { name: '냉동과일', category: '가공/냉동' },
  { name: '햇반', category: '가공/냉동' },
  { name: '즉석국', category: '가공/냉동' },
  { name: '즉석찌개', category: '가공/냉동' },

  // ☕ 음료/간식
  { name: '물', category: '음료/간식' },
  { name: '탄산수', category: '음료/간식' },
  { name: '콜라', category: '음료/간식' },
  { name: '사이다', category: '음료/간식' },
  { name: '주스', category: '음료/간식' },
  { name: '커피원두', category: '음료/간식' },
  { name: '티백', category: '음료/간식' },
  { name: '녹차', category: '음료/간식' },
  { name: '홍차', category: '음료/간식' },
  { name: '코코아파우더', category: '음료/간식' },
];